language: node_js
node_js:
  - "8"

jobs:
  include:
    - stage: init
      script:
        - mkdir -p docs/client
        - mkdir -p docs/server
    - stage: core
      script:
        - echo 'Installing'
        - cd core
        - npm i
        - echo 'Building'
        - npm run build
        - echo 'Running tslint'
        - npm run tslint
        - echo 'Testing'
        - npm test
        - echo 'Done'
    - stage: client
      script:
        - echo 'Installing'
        - cd client
        - npm i
        - echo 'Building'
        - npm run build
        - echo 'Running tslint'
        - npm run tslint
        - echo 'Testing'
        - echo 'Generating Documentation'
        - npm run docs
        - cp -r docs/* ../docs/client

    - stage: server
      script:
        - echo 'Installing'
        - cd server
        - npm i
        - echo 'Building'
        - npm run build
        - echo 'Running tslint'
        - npm run tslint
        - echo 'Testing'
        - echo 'Generating Documentation'
        - npm run docs
        - cp -r docs/* ../docs/server
    - stage: deploy
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $DEPLOY_GITHUB_PAGES
        keep_history: true
        local_dir: "docs"
        on:
          branch: master