dist: bionic
language: node_js
node_js:
  - "10.15.3"

install:
  - npm install -g codecov coveralls
jobs:
  include:
    - stage: core
      script:
        - echo 'Installing'
        - cd core
        - npm i
        - echo 'Building'
        - npm run build
        - echo 'Running tslint'
        - npm run tslint
        - echo 'Testing'
        - npm test
        - npm run coverage
        - cat ./coverage/lcov.info | coveralls ../
        - codecov
    - stage: client
      script:
        - echo 'Installing'
        - cd client
        - npm i
        - echo 'Building'
        - npm run build
        - echo 'Running tslint'
        - npm run tslint
        - echo 'Testing'
        - npm test
        - cat ./coverage/lcov.info | coveralls ../
        - codecov
        - echo 'Generating Documentation'
        - npm run docs
        - cd docs
        - touch .nojekyll
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $DEPLOY_GITHUB_PAGES
        keep_history: true
        local_dir: client/docs
        repo: rolznz/infinitris2-client-docs
        on:
          branch: master
        target_branch: master

    - stage: server
      script:
        - echo 'Installing'
        - cd core
        - npm i
        - npm run build
        - cd ../server
        - npm i
        - echo 'Building'
        - npm run build
        - echo 'Running tslint'
        - npm run tslint
        - echo 'Testing'
        - npm run build-tests
        - npm test
        - npm run coverage
        - cat ./coverage/lcov.info | coveralls ../
        - codecov
        - echo 'Generating Documentation'
        - npm run docs
        - cd docs
        - touch .nojekyll
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $DEPLOY_GITHUB_PAGES
        keep_history: true
        local_dir: server/docs
        repo: rolznz/infinitris2-server-docs
        on:
          branch: master
        target_branch: master
    - stage: integration
      script:
        - echo 'Installing'
        - cd integration
        - npm i
        - echo 'Running tslint'
        - npm run tslint
        - echo 'Testing'
        - npm test