dist: bionic
language: node_js
node_js:
  - "10.15.3"

install:
  - npm install -g codecov coveralls
jobs:
  include:
    - stage: test
      script:
        - (cd core && npm i && npm run tslint && npm test && npm run coverage && codecov)
        - (cd client && npm i && npm run tslint && npm test && codecov)
        - (cd server && npm i && npm run tslint && npm run build-tests && npm test && npm run coverage && codecov)
        - (cd integration && npm i && npm run tslint && npm run test)
    - stage: client-docs
      script:
        (cd client && npm i && npm run docs && cd docs && touch .nojekyll)
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $DEPLOY_GITHUB_PAGES
        keep_history: true
        local_dir: client/docs
        repo: rolznz/infinitris2-client-docs
        on:
          branch: master
        target_branch: master
    - stage: server-docs
      script:
        - (cd server && npm i && npm run docs && cd docs && touch .nojekyll)
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $DEPLOY_GITHUB_PAGES
        keep_history: true
        local_dir: server/docs
        repo: rolznz/infinitris2-server-docs
        on:
          branch: master
        target_branch: master