language: node_js
node_js:
  - "8"

jobs:
  include:
    - stage: core
      script:
        - echo 'Installing'
        - cd core
        - npm i
        - echo 'Building'
        - npm run build
        - echo 'Running tslint'
        - npm run tslint
        - echo 'Testing'
        - npm test
        - npm run coverage
    - stage: client
      script:
        - echo 'Installing'
        - cd client
        - npm i
        - echo 'Building'
        - npm run build
        - echo 'Running tslint'
        - npm run tslint
        - echo 'Testing'
        - echo 'Generating Documentation'
        - npm run docs
        - cd docs
        - touch .nojekyll
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $DEPLOY_GITHUB_PAGES
        keep_history: true
        local_dir: client/docs
        repo: rolznz/infinitris2-client-docs
        on:
          branch: master
        target_branch: master

    - stage: server
      script:
        - echo 'Installing'
        - cd server
        - npm i
        - echo 'Building'
        - npm run build
        - echo 'Running tslint'
        - npm run tslint
        - echo 'Testing'
        - echo 'Generating Documentation'
        - npm run docs
        - cd docs
        - touch .nojekyll
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $DEPLOY_GITHUB_PAGES
        keep_history: true
        local_dir: server/docs
        repo: rolznz/infinitris2-server-docs
        on:
          branch: master
        target_branch: master