import { WorldBackgroundConfig } from '@src/rendering/renderers/infinitris2/WorldBackgroundConfig';

export const space: WorldBackgroundConfig = {
  worldType: 'space',
  floorColor: 0xff00ff,
  hasFloorImage: true,
  blockOutlineColor: 0x00ffff,
  layers: [
    {
      filename: 'theme_space_0.png',
      speedY: 0.1,
      speedX: 0,
      offsetY: 0,
      //portraitScale: 1.5,
    },
    {
      filename: 'theme_space_1.png',
      speedY: 0.05,
      speedX: 0.05,
      offsetY: 0,
      offsetX: 0,
      //portraitScale: 1.5,
    },
    {
      filename: 'theme_space_2.png',
      speedY: 0.1,
      speedX: 0.1,
      offsetY: 0.0,
      offsetX: 0,
      //repeatGap: 5,
      //scale: 0.3,
      //portraitOffsetY: 0.02,
      //portraitScale: 1.5,
    },
    {
      filename: 'theme_space_3.png',
      speedY: 0.2,
      speedX: 0.2,
      offsetX: 0.0,
      offsetY: 0.0,
    },
    {
      filename: 'theme_space_5.png',
      speedY: 0.25,
      speedX: 0.25,
      offsetY: 0.1,
      offsetX: 0.1,
      scale: 0.1,
      repeatGap: 40,
      //portraitOffsetY: 0.15,
    },
    {
      filename: 'theme_space_4.png',
      speedY: 0.3,
      speedX: 0.3,
      offsetY: 0.1,
      offsetX: 0.2,
      scale: 0.25,
      repeatGap: 20,
    },

    {
      filename: 'theme_space_6.png',
      speedY: 0.35,
      speedX: 0.35,
      offsetY: 0.1,
      offsetX: 0.2,
      scale: 0.5,
      repeatGap: 10,
    },
    {
      filename: 'theme_space_7.png',
      speedY: 0.4,
      speedX: 0.4,
      offsetY: 0.025,
      offsetX: 0.3,
      //portraitOffsetY: 0.15,
      scale: 1,
      repeatGap: 5,
    },
    {
      filename: 'theme_space_8.png',
      speedY: 0.5,
      speedX: 0.5,
      offsetY: 0.2,
      //scale: 2,
      //portraitOffsetY: 0.15,
    },
    {
      filename: 'theme_space_9.png',
      speedY: 0.6,
      speedX: 0.6,
      offsetY: 0.25,
      //portraitOffsetY: 0.05,
      //minQuality: 'high',
    },
    {
      filename: 'theme_space_10.png',
      speedY: 0.7,
      speedX: 0.7,
      offsetY: 0.32,
      //portraitOffsetY: 0.05,
      //minQuality: 'high',
    },
    {
      filename: 'theme_space_11.png',
      speedY: 0.8,
      speedX: 0.8,
      offsetY: 0.45,
      //portraitOffsetY: 0.05,
      //minQuality: 'high',
    },
    {
      filename: 'theme_space_12b.png',
      speedY: 0.9,
      speedX: 0.9,
      offsetY: 0.4,
      //portraitOffsetY: 0.05,
      //minQuality: 'high',
    },
    {
      filename: 'theme_space_13.png',
      speedY: 0.5,
      speedX: 0.5,
      offsetY: 0.0,
      //portraitOffsetY: 0.05,
      //minQuality: 'high',
    },
  ],
};
