export enum ServerMessageType {
  JOIN_ROOM_RESPONSE,
  PLAYER_CONNECTED,
  PLAYER_DISCONNECTED,
  BLOCK_CREATED,
  BLOCK_MOVED,
  BLOCK_PLACED,
  BLOCK_DIED,
  BLOCK_DROPPED,
  NEXT_DAY,
  NEXT_SPAWN,
  CHAT,
  PLAYER_TOGGLE_SPECTATING,
}
