enum Routes {
  welcome = '/welcome',
  rooms = '/rooms',
  lobby = '/lobby',
  home = '/',
  credits = '/credits',
  termsOfService = '/tos',
  privacyPolicy = '/privacy',
  profile = '/profile',
  customizeProfile = '/profile/customize',
  login = '/login',
  comingSoon = '/coming-soon',
  singlePlayer = '/single-player',
  settings = '/settings',
  controlSettings = '/settings/controls',
  challenges = '/challenges',
  createChallenge = '/create/challenge',
  loadChallenge = '/create/challenge/load',
  challengeRequired = '/challenge-required',
  scoreboard = '/scoreboard',
  allSet = '/all-set',
  earnCoins = '/earn-coins',
  affiliateProgram = '/affiliate-program',
}

export default Routes;
